-- database/schemas/05_mock_interviews.sql
-- Mock interview sessions (full simulation)

CREATE TABLE IF NOT EXISTS mock_interviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  resume_id UUID REFERENCES resumes(id) ON DELETE SET NULL,
  job_description_id UUID REFERENCES job_descriptions(id) ON DELETE SET NULL,

  -- Interview configuration
  persona_id TEXT NOT NULL,  -- 'emma-hr', 'james-manager', 'sato-tech'
  duration_minutes INTEGER NOT NULL DEFAULT 15,
  focus TEXT,  -- 'behavioral', 'technical', 'mixed'
  difficulty TEXT CHECK (difficulty IN ('easy', 'standard', 'hard')),

  -- Interview plan (generated by AI)
  planned_questions JSONB,  -- Array of planned questions

  -- Results
  verdict TEXT CHECK (verdict IN ('strong_hire', 'hire', 'borderline', 'not_ready')),
  overall_score NUMERIC(5,2),  -- 0-100

  -- Performance breakdown
  communication_score NUMERIC(5,2),
  structure_score NUMERIC(5,2),  -- STAR usage
  role_fit_score NUMERIC(5,2),
  technical_depth_score NUMERIC(5,2),

  -- Feedback & Report
  key_strengths TEXT[],
  key_gaps TEXT[],
  improvement_plan JSONB,  -- 7-day plan
  summary TEXT,

  -- Status
  status TEXT DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'completed', 'abandoned')),

  -- Timestamps
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Q&A exchanges during mock interview
CREATE TABLE IF NOT EXISTS mock_interview_exchanges (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  mock_interview_id UUID REFERENCES mock_interviews(id) ON DELETE CASCADE NOT NULL,

  -- Question
  question_text TEXT NOT NULL,
  question_type TEXT,  -- 'intro', 'behavioral', 'technical', 'closing'
  question_competency TEXT,  -- What this question tests

  -- Answer
  user_transcript TEXT,
  user_audio_url TEXT,
  answer_duration_seconds INTEGER,

  -- AI Evaluation
  answer_score NUMERIC(5,2),
  star_completeness JSONB,  -- Which STAR components were present
  follow_up_needed BOOLEAN DEFAULT false,

  -- Follow-up (if any)
  follow_up_question TEXT,
  follow_up_transcript TEXT,
  follow_up_score NUMERIC(5,2),

  -- Metadata
  exchange_order INTEGER NOT NULL,  -- Order in interview

  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE mock_interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE mock_interview_exchanges ENABLE ROW LEVEL SECURITY;

-- Policies for mock_interviews
CREATE POLICY "Users can view own mock interviews"
  ON mock_interviews FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own mock interviews"
  ON mock_interviews FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own mock interviews"
  ON mock_interviews FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own mock interviews"
  ON mock_interviews FOR DELETE
  USING (auth.uid() = user_id);

-- Policies for mock_interview_exchanges
CREATE POLICY "Users can view exchanges from own interviews"
  ON mock_interview_exchanges FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM mock_interviews
    WHERE mock_interviews.id = mock_interview_exchanges.mock_interview_id
    AND mock_interviews.user_id = auth.uid()
  ));

CREATE POLICY "Users can create exchanges in own interviews"
  ON mock_interview_exchanges FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM mock_interviews
    WHERE mock_interviews.id = mock_interview_exchanges.mock_interview_id
    AND mock_interviews.user_id = auth.uid()
  ));

-- Auto-update timestamps
CREATE TRIGGER update_mock_interviews_updated_at
  BEFORE UPDATE ON mock_interviews
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_mock_interviews_user_id ON mock_interviews(user_id);
CREATE INDEX IF NOT EXISTS idx_mock_interviews_status ON mock_interviews(user_id, status);
CREATE INDEX IF NOT EXISTS idx_mock_exchanges_interview_id ON mock_interview_exchanges(mock_interview_id);
CREATE INDEX IF NOT EXISTS idx_mock_exchanges_order ON mock_interview_exchanges(mock_interview_id, exchange_order);
