-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analysis_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid NOT NULL,
  job_description_id uuid,
  ats_score integer NOT NULL,
  jd_match_score integer,
  skills_fit_score integer NOT NULL,
  analysis_data jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT analysis_results_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT analysis_results_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT analysis_results_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.cover_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  title text NOT NULL DEFAULT 'Cover Letter'::text,
  content text NOT NULL,
  html_content text,
  company_name text,
  position_title text,
  tone text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cover_letters_pkey PRIMARY KEY (id),
  CONSTRAINT cover_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT cover_letters_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT cover_letters_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.gap_defenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  swot_analysis_id uuid,
  gap_type text NOT NULL,
  gap_description text NOT NULL,
  pivot text,
  proof text,
  promise text,
  is_favorite boolean DEFAULT false,
  use_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gap_defenses_pkey PRIMARY KEY (id),
  CONSTRAINT gap_defenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT gap_defenses_swot_analysis_id_fkey FOREIGN KEY (swot_analysis_id) REFERENCES public.swot_analyses(id)
);
CREATE TABLE public.intro_pitches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  title text NOT NULL DEFAULT 'Intro Pitch'::text,
  pitch_text text NOT NULL,
  duration_seconds integer,
  hook text,
  core_message text,
  call_to_action text,
  is_active boolean DEFAULT true,
  practice_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT intro_pitches_pkey PRIMARY KEY (id),
  CONSTRAINT intro_pitches_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id),
  CONSTRAINT intro_pitches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT intro_pitches_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.job_descriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  company text,
  description text NOT NULL,
  requirements jsonb,
  parsed_skills ARRAY,
  competencies ARRAY,
  is_active boolean DEFAULT true,
  source_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_descriptions_pkey PRIMARY KEY (id),
  CONSTRAINT job_descriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.mock_interview_exchanges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  exchange_type text NOT NULL CHECK (exchange_type = ANY (ARRAY['welcome'::text, 'small_talk'::text, 'company_intro'::text, 'behavioral'::text, 'technical'::text, 'situational'::text, 'leadership'::text, 'values'::text, 'follow_up'::text, 'wrap_up'::text])),
  question_text text NOT NULL,
  question_audio_url text,
  user_answer_text text,
  user_answer_audio_url text,
  user_answer_duration_seconds integer,
  transcription_confidence numeric,
  answer_score numeric,
  feedback text,
  strengths ARRAY,
  improvements ARRAY,
  star_components jsonb,
  order_index integer NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  analyzed_at timestamp without time zone,
  CONSTRAINT mock_interview_exchanges_pkey PRIMARY KEY (id),
  CONSTRAINT mock_interview_exchanges_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mock_interview_sessions(id)
);
CREATE TABLE public.mock_interview_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  duration_minutes integer NOT NULL CHECK (duration_minutes = ANY (ARRAY[15, 20, 30])),
  interviewer_voice text NOT NULL,
  interviewer_name text NOT NULL,
  interviewer_gender text NOT NULL CHECK (interviewer_gender = ANY (ARRAY['female'::text, 'male'::text, 'neutral'::text])),
  interviewer_title text,
  company_name text,
  job_title text,
  interview_plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  conversation_history ARRAY DEFAULT '{}'::jsonb[],
  status text NOT NULL DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])),
  current_phase text NOT NULL DEFAULT 'welcome'::text CHECK (current_phase = ANY (ARRAY['welcome'::text, 'small_talk'::text, 'company_intro'::text, 'questions'::text, 'wrap_up'::text, 'completed'::text])),
  current_question_index integer DEFAULT 0,
  total_questions integer NOT NULL,
  started_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  duration_seconds integer,
  overall_score numeric,
  feedback_summary text,
  detailed_feedback jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT mock_interview_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT mock_interview_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT mock_interview_sessions_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT mock_interview_sessions_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.newsletter_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  subscribed_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  source text DEFAULT 'landing_page'::text,
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.practice_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL,
  user_id uuid NOT NULL,
  transcript text NOT NULL,
  audio_url text,
  overall_score numeric,
  star_analysis jsonb,
  clarity_score numeric,
  relevance_score numeric,
  impact_score numeric,
  strengths ARRAY,
  improvements ARRAY,
  summary text,
  duration_seconds integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT practice_answers_pkey PRIMARY KEY (id),
  CONSTRAINT practice_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.practice_questions(id),
  CONSTRAINT practice_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.practice_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  question_text text NOT NULL,
  question_category text,
  difficulty text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  expected_components jsonb,
  order_index integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT practice_questions_pkey PRIMARY KEY (id),
  CONSTRAINT practice_questions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.practice_sessions(id)
);
CREATE TABLE public.practice_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  title text NOT NULL DEFAULT 'Practice Session'::text,
  question_category text,
  total_questions integer DEFAULT 0,
  completed_questions integer DEFAULT 0,
  average_score numeric,
  overall_feedback jsonb,
  status text DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  difficulty text DEFAULT 'medium'::text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  CONSTRAINT practice_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT practice_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT practice_sessions_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT practice_sessions_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  avatar_url text,
  subscription_status text DEFAULT 'free'::text CHECK (subscription_status = ANY (ARRAY['free'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  subscription_price_id text,
  subscription_current_period_end timestamp with time zone,
  stripe_customer_id text UNIQUE,
  ai_tokens_used_this_month integer DEFAULT 0,
  practice_sessions_this_month integer DEFAULT 0,
  mock_interviews_this_month integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  mock_voice_id text DEFAULT 'default'::text,
  mock_avatar_quality text DEFAULT 'medium'::text CHECK (mock_avatar_quality = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'basic'::text, 'pro'::text, 'interview_ready'::text])),
  resume_builds_this_month integer DEFAULT 0,
  job_analyses_this_month integer DEFAULT 0,
  audio_practice_sessions_this_month integer DEFAULT 0,
  monthly_video_credits integer DEFAULT 0,
  purchased_video_credits integer DEFAULT 0,
  preferences jsonb DEFAULT '{}'::jsonb,
  is_admin boolean DEFAULT false,
  preferred_interviewer_voice text DEFAULT 'EXAVITQu4vr4xnSDxMaL'::text,
  preferred_interviewer_gender text DEFAULT 'female'::text CHECK (preferred_interviewer_gender = ANY (ARRAY['female'::text, 'male'::text, 'neutral'::text, 'any'::text])),
  cover_letters_this_month integer DEFAULT 0,
  star_voice_sessions_used integer DEFAULT 0,
  mock_interview_minutes_used integer DEFAULT 0,
  purchased_star_sessions integer DEFAULT 0,
  purchased_mock_minutes integer DEFAULT 0,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.resume_examples (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  job_title text NOT NULL,
  industry text NOT NULL,
  experience_level text NOT NULL CHECK (experience_level = ANY (ARRAY['entry'::text, 'mid'::text, 'senior'::text, 'executive'::text])),
  job_category text,
  specialization text,
  content jsonb NOT NULL,
  raw_text text,
  html_content text,
  pdf_url text,
  ats_score integer CHECK (ats_score >= 0 AND ats_score <= 100),
  keywords ARRAY NOT NULL DEFAULT '{}'::text[],
  power_words_count integer DEFAULT 0,
  quantified_achievements_count integer DEFAULT 0,
  meta_title text NOT NULL,
  meta_description text NOT NULL,
  h1_heading text NOT NULL,
  h2_headings ARRAY DEFAULT '{}'::text[],
  target_keywords ARRAY DEFAULT '{}'::text[],
  canonical_url text,
  view_count integer DEFAULT 0,
  download_count integer DEFAULT 0,
  share_count integer DEFAULT 0,
  conversion_rate numeric,
  is_published boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  quality_score integer CHECK (quality_score >= 0 AND quality_score <= 100),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  template_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  generation_cost numeric DEFAULT 0,
  generation_time_ms integer DEFAULT 0,
  created_by uuid,
  CONSTRAINT resume_examples_pkey PRIMARY KEY (id),
  CONSTRAINT resume_examples_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT resume_examples_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.resume_templates (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['modern'::text, 'classic'::text, 'minimal'::text, 'creative'::text, 'professional'::text, 'bold'::text])),
  config jsonb NOT NULL,
  preview_image_url text,
  thumbnail_url text,
  features ARRAY DEFAULT '{}'::text[],
  tags ARRAY DEFAULT '{}'::text[],
  is_premium boolean DEFAULT false,
  is_published boolean DEFAULT true,
  usage_count integer DEFAULT 0,
  average_rating numeric,
  display_order integer DEFAULT 0,
  accent_color text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resume_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL DEFAULT 'Untitled Resume'::text,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_text text,
  is_active boolean DEFAULT true,
  file_url text,
  ats_score integer,
  last_analyzed_at timestamp with time zone,
  analysis_results jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_base_version boolean DEFAULT false,
  source_resume_id uuid,
  job_description_id uuid,
  jd_match_score integer,
  template_id text DEFAULT 'classic'::text,
  design_settings jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT resumes_source_resume_id_fkey FOREIGN KEY (source_resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resumes_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.star_stories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  title text NOT NULL,
  category text,
  related_question text,
  situation text NOT NULL,
  task text NOT NULL,
  action text NOT NULL,
  result text NOT NULL,
  metrics ARRAY,
  skills_demonstrated ARRAY,
  is_favorite boolean DEFAULT false,
  use_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  polished_answer text,
  coach_notes jsonb,
  source_attempt_id uuid,
  job_description_id uuid,
  CONSTRAINT star_stories_pkey PRIMARY KEY (id),
  CONSTRAINT star_stories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT star_stories_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT star_stories_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tier text NOT NULL UNIQUE CHECK (tier = ANY (ARRAY['free'::text, 'basic'::text, 'pro'::text, 'interview_ready'::text])),
  name text NOT NULL,
  description text,
  price_monthly numeric NOT NULL DEFAULT 0,
  price_yearly numeric,
  stripe_price_id_monthly text,
  stripe_price_id_yearly text,
  is_active boolean DEFAULT true,
  resume_builds_limit integer DEFAULT 0,
  job_analyses_limit integer DEFAULT 0,
  audio_practice_sessions_limit integer DEFAULT 0,
  video_mock_interviews_limit integer DEFAULT 0,
  monthly_video_credits integer DEFAULT 0,
  features jsonb DEFAULT '[]'::jsonb,
  analytics_level text DEFAULT 'basic'::text CHECK (analytics_level = ANY (ARRAY['basic'::text, 'standard'::text, 'advanced'::text])),
  display_order integer DEFAULT 0,
  badge_text text,
  badge_color text,
  highlight_features ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  star_stories_limit integer DEFAULT 0,
  swot_analyses_limit integer DEFAULT 0,
  gap_defenses_limit integer DEFAULT 0,
  intro_pitches_limit integer DEFAULT 0,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.swot_analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  strengths jsonb DEFAULT '[]'::jsonb,
  weaknesses jsonb DEFAULT '[]'::jsonb,
  opportunities jsonb DEFAULT '[]'::jsonb,
  threats jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  last_generated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT swot_analyses_pkey PRIMARY KEY (id),
  CONSTRAINT swot_analyses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT swot_analyses_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT swot_analyses_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.usage_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resource_type text NOT NULL,
  resource_count integer DEFAULT 1,
  estimated_cost_cents integer,
  session_id uuid,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mock_interviews_count integer DEFAULT 0,
  CONSTRAINT usage_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT usage_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);